#!/usr/bin/env python3
"""
CrowdCode: Generate Pull Requests from Feature Request Issues

This script scans for issues labeled 'crowdcode:feature-request' and generates
AI-powered pull requests for each one.
"""

import os
import sys
import json
import re
import yaml
from github import Github
from datetime import datetime

def load_config():
    """Load CrowdCode configuration"""
    config_path = '.github/crowdcode-config.yml'
    try:
        with open(config_path, 'r') as f:
            return yaml.safe_load(f)
    except FileNotFoundError:
        print(f"Warning: Config file {config_path} not found, using defaults")
        return {
            'issue_processing': {
                'max_per_run': 5,
                'labels': {
                    'feature_request': 'crowdcode:feature-request',
                    'pending_pr': 'crowdcode:pending-pr',
                    'ai_generated': 'crowdcode:ai-generated',
                    'voting': 'crowdcode:voting'
                }
            },
            'branches': {
                'prefix': 'crowdcode/feature',
                'base_branch': 'main'
            }
        }

def slugify(text):
    """Convert text to URL-friendly slug"""
    text = text.lower()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_-]+', '-', text)
    text = re.sub(r'^-+|-+$', '', text)
    return text[:50]  # Limit length

def parse_issue_body(body):
    """Parse structured issue body from GitHub issue template"""
    # Simple parser for form responses
    sections = {}
    current_section = None
    
    for line in body.split('\n'):
        line = line.strip()
        if line.startswith('### '):
            current_section = line[4:].strip()
            sections[current_section] = []
        elif current_section and line:
            sections[current_section].append(line)
    
    # Join multi-line sections
    for key in sections:
        sections[key] = '\n'.join(sections[key])
    
    return sections

def generate_pr_description(issue):
    """Generate PR description from issue"""
    sections = parse_issue_body(issue.body)
    
    description = f"""# {issue.title}

🤖 **AI-Generated Feature Implementation**

This PR was automatically generated by CrowdCode in response to issue #{issue.number}.

## Feature Description

{sections.get('Feature Description', 'No description provided')}

## Use Case / Motivation

{sections.get('Use Case / Motivation', 'No use case provided')}

## Acceptance Criteria

{sections.get('Acceptance Criteria', 'No acceptance criteria provided')}

## Implementation Notes

⚠️ **This is an AI-generated implementation and requires PatchPanel review.**

**Note:** This is currently a placeholder PR. Full AI code generation will be implemented in Phase 2.
For now, this demonstrates the CrowdCode workflow:
1. Issue submitted
2. PR generated automatically
3. PatchPanel members vote
4. Feature promoted if approved

## 🗳️ PatchPanel Voting

**Vote Status**: Waiting for votes

To vote on this feature:
- 👍 React with thumbs up to approve
- 👎 React with thumbs down to reject
- 👀 React with eyes if more review needed

Only votes from PatchPanel members count toward promotion.

---

**Related Issue**: #{issue.number}
**Branch**: Will be created on merge
**Status**: 🔄 Awaiting PatchPanel votes
"""
    return description

def main():
    """Main execution"""
    # Get environment variables
    github_token = os.environ.get('GITHUB_TOKEN')
    repo_name = os.environ.get('GITHUB_REPOSITORY')
    dry_run = os.environ.get('DRY_RUN', 'false').lower() == 'true'
    
    if not github_token:
        print("Error: GITHUB_TOKEN environment variable not set")
        sys.exit(1)
    
    if not repo_name:
        print("Error: GITHUB_REPOSITORY environment variable not set")
        sys.exit(1)
    
    print(f"CrowdCode Issue to PR Generator")
    print(f"Repository: {repo_name}")
    print(f"Dry Run: {dry_run}")
    print("-" * 60)
    
    # Load configuration
    config = load_config()
    max_per_run = config['issue_processing']['max_per_run']
    labels = config['issue_processing']['labels']
    branch_prefix = config['branches']['prefix']
    base_branch = config['branches']['base_branch']
    
    # Initialize GitHub client
    gh = Github(github_token)
    repo = gh.get_repo(repo_name)
    
    # Find feature request issues without PR
    print(f"\nSearching for issues labeled '{labels['feature_request']}'...")
    issues = repo.get_issues(
        state='open',
        labels=[labels['feature_request']]
    )
    
    processed = 0
    for issue in issues:
        if processed >= max_per_run:
            print(f"\nReached maximum of {max_per_run} issues per run")
            break
        
        # Check if already has pending PR label
        issue_labels = [label.name for label in issue.labels]
        if labels['pending_pr'] in issue_labels or labels['ai_generated'] in issue_labels:
            print(f"\nSkipping issue #{issue.number}: Already has PR")
            continue
        
        print(f"\n{'[DRY RUN] ' if dry_run else ''}Processing issue #{issue.number}: {issue.title}")
        
        # Generate branch name
        slug = slugify(issue.title.replace('[FEATURE]', '').strip())
        branch_name = f"{branch_prefix}-{issue.number}-{slug}"
        print(f"  Branch name: {branch_name}")
        
        # Generate PR description
        pr_description = generate_pr_description(issue)
        pr_title = issue.title
        
        if not dry_run:
            try:
                # For now, just add labels to indicate PR would be created
                # Full implementation with branch creation and PR will come in Phase 2
                issue.add_to_labels(labels['pending_pr'])
                issue.create_comment(
                    f"🤖 CrowdCode PR generation initiated!\n\n"
                    f"A pull request will be created with AI-generated code.\n"
                    f"Branch: `{branch_name}`\n\n"
                    f"**Note**: Full AI code generation is coming in Phase 2. "
                    f"For now, this demonstrates the CrowdCode workflow structure."
                )
                print(f"  ✓ Added '{labels['pending_pr']}' label")
                print(f"  ✓ Posted comment on issue")
            except Exception as e:
                print(f"  ✗ Error: {e}")
                continue
        else:
            print(f"  [DRY RUN] Would add label '{labels['pending_pr']}'")
            print(f"  [DRY RUN] Would create comment on issue")
        
        processed += 1
    
    print(f"\n{'=' * 60}")
    print(f"Processed {processed} issue(s)")
    print(f"Dry Run: {dry_run}")
    print("Complete!")

if __name__ == '__main__':
    main()
